[package]
authors = ["Ricardo Ghisi Tobaldini <rghisi@gmail.com>"]
name = "hello_elf"
publish = false
version = "0.1.0"
edition = "2024"

[dependencies]
system = { path = "../../system" }
usrlib = { path = "../../usrlib" }
