[workspace]
members = [
    "system",
    "kernel",
    "usrlib",
    "arch/x86_64",
    "apps/shell",
    "apps/dummy",
]

[profile.dev]
panic = "abort"
opt-level = 0

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
