[package]
authors = ["Ricardo Ghisi Tobaldini <rghisi@gmail.com>"]
name = "kernel"
publish = false
version = "0.1.0"
edition.workspace = true

[dependencies]
collections = { path = "../collections" }
system = { path = "../system" }
lazy_static = "1.5.0"
buddy_system_allocator = "0.11.0"
