[package]
authors = ["Ricardo Ghisi Tobaldini <rghisi@gmail.com>"]
name = "kernel"
publish = false
version = "0.1.0"
edition.workspace = true

[dependencies]
system = { path = "../system" }
buddy_system_allocator = "0.11.0"
lazy_static = "1.5.0"
