[package]
authors = ["Ricardo Ghisi Tobaldini <rghisi@gmail.com>"]
name = "usrlib"
publish = false
version = "0.1.0"
edition.workspace = true

[dependencies]
system = { path = "../system" }
collections = { path = "../collections" }