[package]
authors = ["Ricardo Ghisi Tobaldini <rghisi@gmail.com>"]
name = "test_suite"
publish = false
version = "0.1.0"
edition.workspace = true

[dependencies]
system = { path = "../../system" }
usrlib = { path = "../../usrlib" }
