[build]
target = "rosx.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "alloc", "compiler_builtins"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"