[build]
target = "../../arch/x86_64/rosx-user.json"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "link-arg=-T../../apps/hello_elf/linker.ld", "-C", "link-arg=--pie"]
